import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import QueryProvider from "@/components/provider/query-provider";
import AuthInitializer from "./auth-initializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Header />

        {/* Main content expands to fill available space */}
        <main className="flex-grow">
          <QueryProvider><AuthInitializer>{children}</AuthInitializer></QueryProvider>
        </main>

        {/* Footer stays at bottom when content is short */}
        <Footer />

        {/* Toaster stays on top */}
        <Toaster />
      </body>
    </html>
  );
}
